version: '3.3'

services:
  task_manager_db:
    image: mysql:8.0.0
    restart: always
    environment:
      MYSQL_DATABASE: 'task_manager_db'
      MYSQL_USER: 'task_manager'
      MYSQL_PASSWORD: 'task_manager'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3307'

# useful commands
# docker-compose up -d
# docker-compose config